# --- HOSTS ---
h1[0]="lan_h1"
h1[image]="kathara/base"

h2[0]="lan_h2"
h2[image]="kathara/base"

h3[0]="lan_h3"
h3[image]="kathara/base"

h4[0]="lan_h4"
h4[image]="kathara/base"

# --- SERVICE FUNCTIONS (P4 Reflectors) ---
sf1[0]="lan_sf1"
sf1[image]="kathara/p4"

sf2[0]="lan_sf2"
sf2[image]="kathara/p4"

sf3[0]="lan_sf3"
sf3[image]="kathara/p4"

# --- SWITCHES P4 ---
swa[0]="lan_h1"
swa[1]="lan_h2"
swa[2]="swa_swb"
swa[3]="swa_swc"
swa[image]="kathara/p4"

swb[0]="swa_swb"
swb[1]="swb_swc"
swb[2]="swb_swd"
swb[3]="swb_swf"
swb[image]="kathara/p4"

swc[0]="swa_swc"
swc[1]="swb_swc"
swc[2]="swc_swe"
swc[3]="swc_swg"
swc[image]="kathara/p4"

swd[0]="swb_swd"
swd[1]="swd_swf"
swd[2]="lan_sf1"
swd[3]="lan_sf2"
swd[image]="kathara/p4"

swe[0]="swc_swe"
swe[1]="swe_swg"
swe[2]="lan_sf3"
swe[image]="kathara/p4"

swf[0]="swb_swf"
swf[1]="swd_swf"
swf[2]="swf_swg"
swf[3]="swf_swh"
swf[image]="kathara/p4"

swg[0]="swc_swg"
swg[1]="swe_swg"
swg[2]="swf_swg"
swg[3]="swg_swh"
swg[image]="kathara/p4"

swh[0]="swf_swh"
swh[1]="swg_swh"
swh[2]="lan_h3"
swh[3]="lan_h4"
swh[image]="kathara/p4"